pipeline {
      agent any
/*    agent {
        docker {
            image 'maven:3.9.0'
            args '-v /root/.m2:/root/.m2'
        }
    }
*/
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Vulnerability Analysis') {
            steps {
                sh 'mvn org.owasp:dependency-check-maven:check'
            }
        }
        stage('Build Docker Image') {
    	    steps {
        	script {
            	// Copiar el artefacto si es necesario
		sh 'cp target/*.jar dockerfile/'

            	sh 'cd dockerfile/'

            	// Construir la imagen Docker
            	sh 'docker build -f dockerfile/Dockerfile -t my-app-image .'

		sh 'cd ..'

            	// Publicar la imagen en Docker Hub
            	//sh 'docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD'
            	//sh 'docker tag my-app-image $DOCKER_USERNAME/my-app-image:latest'
            	//sh 'docker push $DOCKER_USERNAME/my-app-image:latest'
                }
    	    }
	}
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
